import Contact from "../components/Contact";
import PageTitle from "../components/PageTitle";
import Task from "../components/Task";
import ContactModal from "../components/modals/ContactModal";
import { useState } from "react";

import styles from "../sass/pages/CreateJobNew.module.scss";
import ReactDOM from "react-dom";

const CreateJobNewPage = () => {
  // will create and maintain a Job object state, and save that object to a data object to Firebase
  // other values like inspectionSuccessful, timeLeft, and completionStatus are all auto generated by default, the rest is user input

  const [contactsOpen, setContactsOpen] = useState(false);

  const onOpenContacts = () => {
    setContactsOpen(true);
  };

  const onCloseContacts = () => {
    setContactsOpen(false);
  };

  const DUMMY_CONTACTS = [{firstName: "firstname", lastName: "lastname", phone: "0000000000"}]

  return (
    <>
      <main className={styles["main-content"]}>
        <PageTitle title="Create New Job" />

        <button>BACK</button>
        <button>Delete Job</button>

        <section>
          <label htmlFor="job-title">Job Title</label>
          <input type="text" id="job-title" />
          <label htmlFor="address-street">Street Address</label>
          <input type="text" id="address-street" />
          <label htmlFor="address-city">City</label>
          <input type="text" id="address-city" />
          <label htmlFor="address-state">State</label>
          <input type="text" id="address-state" />
        </section>
        <section>
          <figure>
            <figcaption>Contacts</figcaption>
            {/* display contact list here */}
            <div>
              <Contact
                firstName={DUMMY_CONTACTS?.at(0)?.firstName}
                lastName={DUMMY_CONTACTS?.at(0)?.lastName}
                phone={DUMMY_CONTACTS.at(0)?.phone}
              />
              <button onClick={onOpenContacts}>View Contacts</button>
              {contactsOpen &&
                ReactDOM.createPortal(
                  <ContactModal
                    contactArray={DUMMY_CONTACTS}
                    onCloseContacts={onCloseContacts}
                  />,
                  document.getElementById("overlay-root")!
                )}
            </div>
            <button>+Add Contact</button>
          </figure>

          <figure>
            <figcaption>Notes</figcaption>
            {/* display notes here */}
            <p>Notes are here</p>
            <button>+Add Notes</button>
          </figure>
        </section>
        <section id="task-list">
          <ul>
            {/* display list here */}
            <>
              <Task
                task={{
                  note: "",
                  description: "Task number one of many",
                  completed: false,
                  cost: "",
                }}
              />
              <button>Edit Note</button>
            </>
            <>
              <Task
                task={{
                  note: "This one has a note attached",
                  description: "Task number one of many",
                  completed: false,
                  cost: "200.21",
                }}
              />
              <button>Edit Note</button>
            </>
            <div>
              <input type="text" id="new-task" placeholder="Task" />
              <button>+ Add Task</button>
            </div>
          </ul>
        </section>
        <section>
          <label htmlFor="priority">Priority:</label>

          <select id="priority" defaultValue={"medium"}>
            <option value="low">Low</option>
            <option value="medium">Medium</option>
            <option value="high">High</option>
          </select>

          <label htmlFor="finish-date">Expected Completion Date</label>
          <input type="date" id="finish-date" />
        </section>
        <button>Create Job</button>
      </main>
    </>
  );
};

export default CreateJobNewPage;
